.
.TH logrecorder 1 "2019-11-18" "v1.5.2" "logrecorder man page"

.SH NAME
logrecorder \- simple log keeping program

.SH SYNOPSIS
.B logrecorder
.RB [ \-\-help ]
.RB [ \-\-version ]
.RB [ \-\-info ]
.RB [ \-\-cli ]
.RB [ \-\-gui ]
.RB [ \-\-path
.IR path ]


.SH DESCRIPTION
A basic CLI/GUI program which allows you to write into a designated text file with timestamps. A diary, log keeping program if you will.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help message and exit.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information and exit.
.TP
\fB\-i\fR, \fB\-\-info\fR
Print currently set path to logs file and exit.
.TP
\fB\-c\fR, \fB\-\-cli\fR
Launch the program in CLI instead of GUI in Windows.
.TP
\fB\-g\fR, \fB\-\-gui\fR
Launch the program in GUI instead of CLI.
.TP
\fB\-p\fR, \fB\-\-path\fR \fIpath\fR
Set and save logs file path to config file. Tilde (~) could be used instead of $HOME.

.SH DEFAULTS
Default configuration and logs file paths are as follows:

.SS CONFIG PATH
.IP Linux:
.B /home/$USER/.config/logrecorder/
.IP Windows:
.B C:/Users/$USER/Documents/logrecorder/

.SS LOGS PATH
.IP Linux:
.B /home/$USER/logrecorder.logs.txt
.IP Windows:
.B C:/Users/$USER/logrecorder.logs.txt

.SH USAGE
.TP
\fBENTER\fR, \fBNUMPADENTER\fR
Record the input to the file with a timestamp (even if it's an empty string) and in GUI also clear the text box afterwards.
.TP
\fBCTRL\-C\fR
In CLI, terminate the program.

.SH AUTHOR
Edvin Boul <edvinboul at gmail dot com>

.SH COPYRIGHT
\fIlogrecorder\fR is licensed under GNU General Public License v3.0 (GPL\-3.0), see LICENSE file.
