.
.TH logrecorder 1 "2019-07-26" "v1.3.4" "logrecorder man page"

.SH NAME
logrecorder \- simple log keeping program

.SH SYNOPSIS
.B logrecorder
.RB [ \-\-path
.IR directory ]
.RB [ \-\-file
.IR filename ]
.RB [ \-\-del ]
.RB [ \-\-cli ]
.RB [ \-\-gui ]
.RB [ \-\-version ]
.RB [ \-\-help ]


.SH DESCRIPTION
A basic CLI/GUI program which allows you to write into a designated text file with timestamps. A diary, log keeping program if you will.

.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-path\fR \fIdirectory\fR
Set and save destination directory to the config file.
.TP
\fB\-f\fR, \fB\-\-file\fR \fIfilename\fR
Set and save target filename to the config file.
.PP
Creating the config file will override path values of in\-program dictionary (dict_strings: path_dir, name_filename).
.TP
\fB\-d\fR, \fB\-\-del\fR
Delete the configuration file and folder. A yes/no prompt will be given to the user.
.TP
\fB\-c\fR, \fB\-\-cli\fR
Launch the program in CLI instead of GUI in Windows. When combining with path options, CLI must come last.
.TP
\fB\-g\fR, \fB\-\-gui\fR
Launch the program in GUI instead of CLI. When combining with path options, GUI must come last.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information and exit.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help message and exit.

.SH USAGE
.TP
\fBENTER\fR, \fBNUMPADENTER\fR
Record the input to the file with a timestamp (even if it's an empty string) and in GUI also clear the text box afterwards.
.TP
\fBCTRL\-C\fR
In CLI, terminate the program.

.SH AUTHOR
Edvin Boul <edvinboul at gmail dot com>

.SH COPYRIGHT
\fIlogrecorder\fR is licensed under GNU General Public License v3.0 (GPL\-3.0), see LICENSE file.
